name: Update Air Quality and Weather Forecast

on:
  schedule:
    - cron: '0 6 * * *'  # Run daily at 6:00 UTC
  workflow_dispatch:  # Allows manual trigger

jobs:
  update_forecast:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          pip install -r .github/workflows/requirements.txt

      - name: Set environment variables for API Keys
        run: |
          echo "HOPSWORKS_API_KEY=${{ secrets.HOPSWORKS_API_KEY }}" >> $GITHUB_ENV

      - name: Run update_daily
        run: |
          jupyter nbconvert --to notebook --execute --inplace notebooks/lab1/2.Update_daily.ipynb

      - name: Run batch
        run: |
          jupyter nbconvert --to notebook --execute --inplace notebooks/lab1/4.Batch_inference.ipynb
